### ISSUE TITLE
ImportError: cannot import name '_pafprocess' from 'tf_pose.pafprocess'

### ISSUE THREAD

**Issue by ssz5450** [gsethi2409/tf-pose-estimation#20]
File "F:\SDXX\tfopenpose\openpose\tf_pose\pafprocess\pafprocess.py", line 13, in <module>
    from . import _pafprocess
ImportError: cannot import name '_pafprocess' from 'tf_pose.pafprocess'

**Comment by murasakirua** [comment]
Hello, I have the same problem. How do you solve it?

**Comment by AndresKlagges-OCL** [comment]
The solution here might be to build the c++ library, run the following commands:
- cd tf_pose/pafprocess/
- swig -python -c++ pafprocess.i 
- python setup.py build_ext --inplace

**Comment by keerthanarangineni** [comment]
running build_ext
building '_pafprocess' extension
swigging pafprocess.i to pafprocess_wrap.cpp
swig.exe -python -c++ -o pafprocess_wrap.cpp pafprocess.i
"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\core\include -I. -IC:\Users\user\AppData\Local\Programs\Python\Python311\include -IC:\Users\user\AppData\Local\Programs\Python\Python311\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\ATLMFC\include" "-IC:\Program Files\Microsoft Visual 
Studio\2022\Community\VC\Auxiliary\VS\include" /EHsc /Tppafprocess.cpp /Fobuild\temp.win-amd64-cpython-311\Release\pafprocess.obj
pafprocess.cpp
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\yvals.h(21): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory
error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2                                           

By doing above steps i am getting this error can any one help me to resolve this

**Comment by dilwolf** [comment]
Thank you, buddy. It worked on my ubuntu 22.04

**Comment by GenAI524** [comment]
for running on Windows, how to do?
